# Generated by Django 3.1 on 2020-08-13 08:45

import randomfilestorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=randomfilestorage.storage.RandomFileName('images/'))),
                ('annotation', models.JSONField()),
            ],
        ),
    ]
